import json
import os
import subprocess
import time
import urllib.error
import urllib.request
from pathlib import Path

BASE = "http://127.0.0.1:18080"
ROOT = Path(__file__).resolve().parents[1]
DB_FILE = "/tmp/finshare-test.db"


def req(method, path, payload=None, token=None):
    data = None
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    if payload is not None:
        data = json.dumps(payload).encode()

    request = urllib.request.Request(f"{BASE}{path}", data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(request, timeout=4) as res:
            return res.status, json.loads(res.read().decode() or "{}")
    except urllib.error.HTTPError as e:
        body = e.read().decode() or "{}"
        try:
            parsed = json.loads(body)
        except Exception:
            parsed = {"error": body}
        return e.code, parsed


def start_server():
    env = os.environ.copy()
    env["DATABASE_URL"] = f"sqlite:///{DB_FILE}"
    env["APP_SECRET"] = "test-secret"
    env["PORT"] = "18080"
    Path(DB_FILE).unlink(missing_ok=True)
    proc = subprocess.Popen(["python3", "backend/app.py"], cwd=str(ROOT), env=env)

    for _ in range(40):
        try:
            code, _ = req("GET", "/api/health")
            if code == 200:
                return proc
        except Exception:
            pass
        time.sleep(0.2)

    proc.terminate()
    raise RuntimeError("server failed to start")


def test_transfer_and_session_and_2fa_flow():
    proc = start_server()
    try:
        code, alice_login = req("POST", "/api/login", {"email": "alice@fintrade.com", "password": "alice123"})
        assert code == 200
        alice_token = alice_login["token"]

        code, setup = req("POST", "/api/2fa/setup", {}, alice_token)
        assert code == 200
        secret = setup["secret"]
        assert len(secret) >= 16

        # OTP generated by asking backend algorithm via inline python for deterministic compatibility
        otp = subprocess.check_output(
            [
                "python3",
                "-c",
                (
                    "import time,base64,hmac,hashlib,sys;"
                    "s=sys.argv[1];"
                    "k=base64.b32decode(s+'='*(-len(s)%8),casefold=True);"
                    "c=int(time.time()/30).to_bytes(8,'big');"
                    "d=hmac.new(k,c,hashlib.sha1).digest();"
                    "o=d[-1]&15;"
                    "v=int.from_bytes(d[o:o+4],'big')&0x7fffffff;"
                    "print(str(v%1000000).zfill(6))"
                ),
                secret,
            ]
        ).decode().strip()

        code, _ = req("POST", "/api/2fa/enable", {"otp": otp}, alice_token)
        assert code == 200

        code, need_otp = req("POST", "/api/login", {"email": "alice@fintrade.com", "password": "alice123"})
        assert code == 202
        assert need_otp["requires_2fa"] is True

        code, alice_login_2 = req(
            "POST", "/api/login", {"email": "alice@fintrade.com", "password": "alice123", "otp": otp}
        )
        assert code == 200
        alice_token_2 = alice_login_2["token"]

        code, sessions = req("GET", "/api/sessions", token=alice_token_2)
        assert code == 200
        assert len(sessions["sessions"]) >= 2

        old_session_id = [s["id"] for s in sessions["sessions"] if s["id"] != sessions["current_session_id"]][0]
        code, _ = req("POST", "/api/sessions/revoke", {"session_id": old_session_id}, alice_token_2)
        assert code == 200

        # old token should now be unauthorized
        code, _ = req("GET", "/api/me", token=alice_token)
        assert code == 401

        code, transfer = req(
            "POST",
            "/api/transfers",
            {"to_email": "bob@fintrade.com", "symbol": "ACME", "quantity": 3, "price_per_share": 10.0},
            alice_token_2,
        )
        assert code == 201
        tid = transfer["transfer_id"]

        code, comp_login = req(
            "POST", "/api/login", {"email": "compliance@fintrade.com", "password": "comply123"}
        )
        assert code == 200
        comp_token = comp_login["token"]

        code, _ = req("POST", f"/api/transfers/{tid}/approve", {}, comp_token)
        assert code == 200
        code, _ = req("POST", f"/api/transfers/{tid}/execute", {}, comp_token)
        assert code == 200
    finally:
        proc.terminate()
        proc.wait(timeout=4)
